---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
        Controversial/CamelCaseMethodName:
                enabled: false
        CleanCode/StaticAccess:
                enabled: false
        Naming/ShortVariable:
                enabled: false
        Design/ExitExpression:
                enabled: false
ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.php"
exclude_paths:
- tests/
