---
plugins:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  eslint:
    enabled: true
    checks:
      no-alert:
        enabled: false
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
        Controversial/CamelCaseMethodName:
                enabled: false
        Controversial/CamelCaseVariableName:
                enabled: false
        CleanCode/StaticAccess:
                enabled: false
        Naming/ShortVariable:
                enabled: false
        Design/ExitExpression:
                enabled: false
exclude_patterns:
- "core/library/SOAP.php"
- "tests/"
- "core/ui/behaviors/colorbox.js"
- "core/ui/behaviors/dropzone.js"
- "core/library/AdminTable.php"